version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_rag_unlar
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Argentina/La_Rioja
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n/workflows:/workflows:ro   # Monta la carpeta de workflows en modo lectura
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Importa todos los JSON de la carpeta y después arranca n8n
    command: /bin/sh -c "n8n import:workflow --separate --input=/workflows && n8n start"